[project]
name = "localAgent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.14.0",
    "browser-use>=0.11.13",
    "bs4>=0.0.2",
    "deepagents>=0.6.12",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "langchain>=1.3.14",
    "langchain-chroma>=1.1.0",
    "langchain-openai>=1.3.5",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.9",
    "markdownify>=1.2.3",
    "ollama>=0.6.2",
    "playwright>=1.61.0",
    "playwright-stealth>=2.0.3",
    "pypdf>=6.14.2",
    "python-dotenv>=1.2.2",
    "streamlit>=1.59.2",
    "textract>=2.0.0",
    "torch>=2.13.0",
    "transformers>=5.14.1",
]
